# Generated by Django 3.1.14 on 2023-04-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
